/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_mvc_unsika;

import agung.view.ViewBarangInternal;
import agung.view.ViewPelangganInternal;
import agung.view.ViewPemasokInternal;
import agung.view.ViewTransaksi;
import javax.swing.JFrame;

/**
 *
 * @author hp
 */
public class app_utama extends javax.swing.JFrame {

    /**
     * Creates new form app_utama
     */
    public app_utama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopUtama = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuMasterPelanggan = new javax.swing.JMenuItem();
        menuMasterBarang = new javax.swing.JMenuItem();
        menuMasterPemasok = new javax.swing.JMenuItem();
        menuMasterUser = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopUtama.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout desktopUtamaLayout = new javax.swing.GroupLayout(desktopUtama);
        desktopUtama.setLayout(desktopUtamaLayout);
        desktopUtamaLayout.setHorizontalGroup(
            desktopUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopUtamaLayout.setVerticalGroup(
            desktopUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Program Point of Sales");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Master");

        menuMasterPelanggan.setText("Master Pelanggan");
        menuMasterPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(menuMasterPelanggan);

        menuMasterBarang.setText("Master Barang");
        menuMasterBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterBarangActionPerformed(evt);
            }
        });
        jMenu2.add(menuMasterBarang);

        menuMasterPemasok.setText("Master Pemasok");
        menuMasterPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterPemasokActionPerformed(evt);
            }
        });
        jMenu2.add(menuMasterPemasok);

        menuMasterUser.setText("Master User");
        jMenu2.add(menuMasterUser);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi Barang");

        jMenuItem4.setText("Transaksi (POS)");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopUtama)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopUtama)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMasterPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterPelangganActionPerformed
        // TODO add your handling code here:
        ViewPelangganInternal pelanggan = new ViewPelangganInternal();
        this.desktopUtama.add(pelanggan);
        pelanggan.show();
    }//GEN-LAST:event_menuMasterPelangganActionPerformed

    private void menuMasterBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterBarangActionPerformed
        // TODO add your handling code here:
        ViewBarangInternal barang = new ViewBarangInternal();
        this.desktopUtama.add(barang); 
        barang.show();
    }//GEN-LAST:event_menuMasterBarangActionPerformed

    private void menuMasterPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterPemasokActionPerformed
        // TODO add your handling code here:
        ViewPemasokInternal pemasok = new ViewPemasokInternal();
        this.desktopUtama.add(pemasok); 
        pemasok.show();
    }//GEN-LAST:event_menuMasterPemasokActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ViewTransaksi vT = new ViewTransaksi();
        this.desktopUtama.add(vT);
        vT.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuMasterBarang;
    private javax.swing.JMenuItem menuMasterPelanggan;
    private javax.swing.JMenuItem menuMasterPemasok;
    private javax.swing.JMenuItem menuMasterUser;
    // End of variables declaration//GEN-END:variables
}
